# Generated by Django 5.0.3 on 2024-03-26 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='biere_bouteille',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('pImage', models.URLField()),
                ('medal', models.CharField(choices=[('BLANCHE', 'Blanche'), ('BLONDE', 'Blonde'), ('AMBREE', 'Ambree'), ('BRUNE', 'Brune')], max_length=7)),
                ('price', models.DecimalField(decimal_places=2, max_digits=4)),
                ('is_online', models.BooleanField(default=False)),
                ('is_special', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='biere_pression',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('pImage', models.URLField()),
                ('price_25cl', models.DecimalField(decimal_places=2, max_digits=4)),
                ('price_50cl', models.DecimalField(decimal_places=2, max_digits=4)),
                ('is_online', models.BooleanField(default=False)),
                ('is_special', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='cafe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('pImage', models.URLField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=4)),
                ('is_online', models.BooleanField(default=False)),
                ('is_special', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='soft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('pImage', models.URLField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=4)),
                ('is_online', models.BooleanField(default=False)),
                ('is_special', models.BooleanField(default=False)),
            ],
        ),
    ]
