# Generated by Django 5.0.3 on 2024-03-26 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Frite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('lien_image', models.URLField()),
                ('description', models.CharField(max_length=255)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=4)),
                ('en_ligne', models.BooleanField(default=False)),
                ('du_moment', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Kid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('lien_image', models.URLField()),
                ('description', models.CharField(max_length=255)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=4)),
                ('en_ligne', models.BooleanField(default=False)),
                ('du_moment', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='frites',
        ),
        migrations.DeleteModel(
            name='kids_corner',
        ),
        migrations.RenameField(
            model_name='burger',
            old_name='is_online',
            new_name='du_moment',
        ),
        migrations.RenameField(
            model_name='burger',
            old_name='is_special',
            new_name='en_ligne',
        ),
        migrations.RenameField(
            model_name='burger',
            old_name='pImage',
            new_name='lien_image',
        ),
        migrations.RenameField(
            model_name='burger',
            old_name='name',
            new_name='nom',
        ),
        migrations.RenameField(
            model_name='burger',
            old_name='price',
            new_name='prix',
        ),
        migrations.RenameField(
            model_name='dessert',
            old_name='is_online',
            new_name='du_moment',
        ),
        migrations.RenameField(
            model_name='dessert',
            old_name='is_special',
            new_name='en_ligne',
        ),
        migrations.RenameField(
            model_name='dessert',
            old_name='pImage',
            new_name='lien_image',
        ),
        migrations.RenameField(
            model_name='dessert',
            old_name='price',
            new_name='prix',
        ),
        migrations.RenameField(
            model_name='dwitch',
            old_name='is_online',
            new_name='du_moment',
        ),
        migrations.RenameField(
            model_name='dwitch',
            old_name='is_special',
            new_name='en_ligne',
        ),
        migrations.RenameField(
            model_name='dwitch',
            old_name='pImage',
            new_name='lien_image',
        ),
        migrations.RenameField(
            model_name='dwitch',
            old_name='price',
            new_name='prix',
        ),
        migrations.RenameField(
            model_name='salade',
            old_name='is_online',
            new_name='du_moment',
        ),
        migrations.RenameField(
            model_name='salade',
            old_name='is_special',
            new_name='en_ligne',
        ),
        migrations.RenameField(
            model_name='salade',
            old_name='pImage',
            new_name='lien_image',
        ),
        migrations.RenameField(
            model_name='salade',
            old_name='price',
            new_name='prix',
        ),
    ]
