# Generated by Django 5.0.3 on 2024-03-26 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_frite_kid_delete_frites_delete_kids_corner_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dessert',
            old_name='name',
            new_name='nom',
        ),
        migrations.RenameField(
            model_name='dwitch',
            old_name='name',
            new_name='nom',
        ),
        migrations.RenameField(
            model_name='frite',
            old_name='name',
            new_name='nom',
        ),
        migrations.RenameField(
            model_name='kid',
            old_name='name',
            new_name='nom',
        ),
        migrations.RenameField(
            model_name='salade',
            old_name='name',
            new_name='nom',
        ),
    ]
